name: Gerar APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pegar código
      uses: actions/checkout@v4

    - name: Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependências
      run: npm install

    - name: Build React
      run: npm run build

    - name: Instalar Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Configurar Android SDK
      uses: android-actions/setup-android@v3

    - name: Instalar Capacitor
      run: npm install @capacitor/android

    - name: Adicionar Android
      run: npx cap add android

    - name: Copiar build
      run: npx cap copy android

    - name: Gerar APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: NossoGranel-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
